### ISSUE TITLE
Eigenen Layout-Manager implementieren

### ISSUE THREAD

**Issue by highestPACE** [WoBen07/Othello_Spiel#29]
U.A. um sicherzustellen, dass die BoardView quadratisch bleibt

**Comment by Michael58432** [comment]
habe einen generischen layout manager als proportionalLayoutManager implementiert, die derzeitige ausfuerung gibt das gleiche fenstenr und verhalten wie schon zuvor aus. Muss je nach bedarf abgeaendert werden um das gewollte verhalten zu erziehlen.

**Comment by Michael58432** [comment]
auch wenn ich die derzeitige variante mit einer permanenten groese des Fensters ganz gut finde
